### PR TITLE
Adapting PHP 8.1 & PHP 8.2

### PR DESCRIPTION
**Pull request by devajmeireles**
This PR aims to introduce support to PHP 8.1 and PHP 8.2

### CODE REVIEW

**Comment by joshhanley** [comment]
@devajmeireles thanks for the PR! It should already support PHP 8.1 and 8.2 because of the `^8.0` constraint. Is it not working for you? Going to close for now, but if I'm wrong, I'll reopen it 🙂

**Comment by devajmeireles** [comment]
> @devajmeireles thanks for the PR! It should already support PHP 8.1 and 8.2 because of the `^8.0` constraint. Is it not working for you? Going to close for now, but if I'm wrong, I'll reopen it 🙂

@joshhanley ,

I think you're wrong, but feel free to ignore this PR. The constraint `^8.0` means that PHP 8.1 or 8.2 will not be accepted.

CleanShot 2023-10-03 at 10 14 26

**Comment by joshhanley** [comment]
@devajmeireles ah thanks for the screenshot! Can you screenshot the whole terminal so I can read the bit cut off at the right? Thanks!

**Comment by devajmeireles** [comment]
> @devajmeireles ah thanks for the screenshot! Can you screenshot the whole terminal so I can read the bit cut off at the right? Thanks!

CleanShot 2023-10-03 at 10 19 00

**Comment by joshhanley** [comment]
@devajmeireles thanks! It looks like your issue is because you're using Livewire V3. This package is for V2 only (at this stage). I'm hoping to get Livewire Dusk testing out of the box in Livewire core, so haven't focused my attention on making this compatible with V2.

Just also checked, we're also already running tests for PHP 8.1 and 8.2 🙂

image

**Pull request closed without merging**
